### ISSUE TITLE
Markdown in submodules not working right now

### ISSUE THREAD

**Issue by kmindi** [kmindi/CryptoExamples#13]
I merged the pull request that should have been about putting the markdown files into the submodules, but it is not working right now. 

I am rolling back the changes until it is working.

**Comment by Schwamm007** [comment]
This behaviour happens due to the fact that, before the merge, the paths to the submodules have been hardcoded again. While the full submodule then is not taken into care by jekyll, it can't find the markdown files. That is also why you had to put them back into the main repo and adjust the relative paths again. But honestly, this is not what we want to achieve. I wonder why it got merged anyway with the hardcoded undone way, tbh.

**Comment by kmindi** [comment]
I know that's why I opened this issue :P I merged it because I thought it worked. Not your fault of course :)
